#!/bin/bash

xsetroot -cursor_name left_ptr
screenkey &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config=$HOME/.config/bspwm/picom.conf &

bspc monitor LVDS1 -d 1 2 3 4 5 6 

# tanzimate node ha
bspc config border_width 2
bspc config window_gap 15
bspc config split_ratio 0.62
###################################
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme spiral



# load script sort_monitor age monitor dovom vasl bashe

if [ -x $HOME/.config/bspwm/scripts/sort_monitors ]; then
	sh $HOME/.config/bspwm/scripts/sort_monitors
fi
